# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-22 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='\u680f\u76ee\u540d\u79f0')),
                ('slug', models.CharField(db_index=True, max_length=256, verbose_name='\u680f\u76ee\u7f51\u5740')),
                ('intro', models.TextField(default='', verbose_name='\u680f\u76ee\u7b80\u4ecb')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': '\u680f\u76ee',
                'verbose_name_plural': '\u680f\u76ee',
            },
        ),
    ]
